api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('large-tier-queue', views.LargeTierQueueViews)
router.register('report-queue', views.ReportQueueViews)
router.register('pedigrees', views.PedigreeViews, basename='Pedigree')
router.register('pedigree-images', views.PedigreeImageViews, basename='PedigreeImage')
router.register('breeders', views.BreederViews, basename='Breeder')
router.register('breeds', views.BreedViews, basename='Breed')
router.register('breed-groups', views.BreedGroupViews, basename='BreedGroup')
router.register('services', views.ServicesViews, basename='services')
router.register('faq', views.FaqViews, basename='faq')
router.register('bolton', views.BoltonViews, basename='bolton')
router.register('kinship', views.KinshipViews, basename='kinship')
router.register('data_validation', views.DataValidatorViews, basename='data_validation')
router.register('stud_advisor', views.StudAdvisorViews, basename='stud_advisor')
router.register('attached-service', views.AttachedServiceViews, basename='AttachedService')
router.register('birth_notification', views.BirthNotificationViews, basename='BirthNotification')
router.register('bn_child', views.BnChildViews, basename='BnChild')
router.register('updates', views.UpdateViews, basename='updates')
#router.register('authenticate', views.Authenticate)

urlpatterns = [
    path('', include(router.urls)),
    path('api-token-auth', views.CustomAuthToken.as_view()),
    path('membership-add-edit-user', views.membership_add_edit_user)
]

breed/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.breeds, name='breeds'),
    path('new_breed/', views.new_breed_form, name='new_breed_form'),
    path('<int:breed_id>/edit_breed/', views.edit_breed_form, name='edit_breed_form'),
    path('<int:breed_id>/', views.view_breed, name='view_breed'),
]

cloudlines/urls.py
from django.contrib import admin
from django.urls import path, include
from cloud_lines import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('extras/', views.extras, name='extras'),
    path('faqs/', views.faqs, name='faqs'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('order/', views.order, name='order'),
    path('order/<int:service>', views.order, name='order'),
    path('blog/', views.blog, name='blog'),
    path('blog-article/<int:id>/<str:title>', views.blog_article, name='blog_article'),
    path('delete_blog/<int:id>', views.delete_blog, name='delete_blog'),
    path('privacy-policy/', views.privacy_policy, name='privacy'),
    path('know_more/', views.know_more, name='know_more'),
    path('order/subscribe', views.order_subscribe, name='order_subscribe'),
    path('order/success/<int:attached_service_id>/', views.order_success, name='order_success'),
    path('pedigree/', include('pedigree.urls')),
    path('breeders/', include('breeder.urls')),
    path('breeds/', include('breed.urls')),
    path('breed_groups/', include('breed_group.urls')),
    path('account/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('support/', include('support.urls')),
    path('impex/', include('impex.urls')),
    path('approvals/', include('approvals.urls')),
    path('dashboard', views.dashboard, name='dashboard'),
    path('select_graph', views.select_graph, name='select_graph'),
    path('api/', include('api.urls')),
    path('metrics/', include('metrics.urls')),
    path('bolton/', include('boltons.urls')),
    path('birth_notification/', include('birth_notifications.urls')),
    path('memberships/', include('memberships.urls')),
    path('reports/', include('reports.urls')),
    path('primary_account/<str:service>', views.activate_primary_account, name='primary_account'),
    path('build/<int:build_id>', views.build, name='build'),
    path('get_build_status', views.get_build_status, name='get_build_status'),
    path('gdpr/', views.gdpr, name='gdpr'),
    path('robots.txt', views.robots)
]

breed/models.py
from django.db import models
from account.models import AttachedService
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    return 'acc_{0}_{1}/{2}'.format(instance.account.id, instance.account.domain.replace('https://', ''), filename)


class Breed(models.Model):
    account = models.ForeignKey(AttachedService, on_delete=models.SET_NULL, blank=True, null=True)
    breed_name = models.CharField(max_length=100)
    image = models.ImageField(blank=True, upload_to=user_directory_path)
    breed_description = models.TextField(max_length=2000, blank=True)
    custom_fields = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    mk_threshold = models.DecimalField(max_digits=6, decimal_places=4, verbose_name='Mean Kinship threshold',
                                       help_text="This value dictates how potential males are selected when compared"
                                                 "with females. The MK value of the selected female, plus or minus"
                                                 " this figure, determines the acceptable range of MK values in the "
                                                 "male population, for a breeding match.",
                                       blank=True, null=True, default=0.0000)

    breed_admins = models.ManyToManyField(User, related_name='breed_admins', blank=True)

    def __str__(self):
        return self.breed_name

breed/forms.py
from .models import Breed
from django import forms
from django.utils.translation import gettext_lazy as _


class BreedForm(forms.ModelForm):
    class Meta:
        model = Breed
        fields = '__all__'
        exclude = ('account',)
        help_texts = {
            'breed_name': _('e.g. Greyhound, Siamese, Shetland, etc'),
            'image': _('A great picture to depict the breed.'),
            'breed_description': _('What are the common attributes about this breed?')
        }
        widgets = {
            'breed_description': forms.Textarea(attrs={'rows': 4, 'cols': 15, 'maxlength': 2000,}),
        }

breed/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.models import User
from .models import Breed
from .forms import BreedForm
from account.views import is_editor, get_main_account, has_permission, redirect_2_login
import json


@login_required(login_url="/account/login")
def breeds(request):
    attached_service = get_main_account(request.user)
    breeds = Breed.objects.filter(account=attached_service)
    if len(breeds) == 1:
        return redirect('view_breed', breeds[0].id)
    else:
        return render(request, 'breeds.html', {'breeds': breeds,})


@login_required(login_url="/account/login")
def new_breed_form(request):
    # check if user has permission
    if request.method == 'GET':
        if not has_permission(request, {'read_only': False, 'contrib': False, 'admin': True, 'breed_admin': False}):
            return redirect_2_login(request)
    elif request.method == 'POST':
        if not has_permission(request, {'read_only': False, 'contrib': False, 'admin': True, 'breed_admin': False}):
            raise PermissionDenied()
    else:
        raise PermissionDenied()
    
    breed_form = BreedForm(request.POST or None, request.FILES or None)
    attached_service = get_main_account(request.user)

    try:
        custom_fields = json.loads(attached_service.custom_fields)
    except json.decoder.JSONDecodeError:
        custom_fields = {}

    if request.method == 'POST':
        if breed_form.is_valid():
            # go through the input breed admins
            breed_admin_index = 0
            breed_admins = []
            while request.POST.get(f'breed_admin-{breed_admin_index}'):
                username = request.POST.get(f'breed_admin-{breed_admin_index}')
                breed_admin_index += 1
                
                # try to get the breed admin
                try:
                    breed_admin = User.objects.get(username=username)
                except User.DoesNotExist:
                    return HttpResponse(json.dumps({"result": "fail", "msg": f"{username} is not a user!"}))
                
                # check they're not the owner
                if breed_admin == attached_service.user.user:
                    return HttpResponse(json.dumps({"result": "fail", "msg": f"{username} is the owner of the account!"}))
                
                # remove from admins, if they're there
                if breed_admin in attached_service.admin_users.all():
                    attached_service.admin_users.remove(breed_admin)

                # remove from contributors, if they're there
                if breed_admin in attached_service.contributors.all():
                    attached_service.contributors.remove(breed_admin)

                # remove from read_only_users, if they're there
                if breed_admin in attached_service.read_only_users.all():
                    attached_service.read_only_users.remove(breed_admin)
                
                # append breed admin to list
                breed_admins.append(breed_admin)
            
            if isinstance(breed_form['mk_threshold'].value(), float):
                mk = breed_form['mk_threshold'].value()
            else:
                mk = 0.0000

            breed = Breed.objects.create(account=attached_service,
                                         breed_name=breed_form['breed_name'].value(),
                                         breed_description=breed_form['breed_description'].value(),
                                         mk_threshold=mk)
            breed.save()
            try:
                breed.image = request.FILES['image']
            except MultiValueDictKeyError:
                pass

            try:
                custom_fields = json.loads(attached_service.custom_fields)

                for id, field in custom_fields.items():
                    custom_fields[id]['field_value'] = request.POST.get(custom_fields[id]['fieldName'])
            except json.decoder.JSONDecodeError:
                pass

            breed.custom_fields = json.dumps(custom_fields)
            
            # add breed admins to breed, and save
            for breed_admin in breed_admins:
                breed.breed_admins.add(breed_admin)
            breed.save()
            return HttpResponse(json.dumps({"result": "success"}))

    else:
        breed_form = BreedForm()

    return render(request, 'new_breed_form_base.html', {'breed_form': breed_form,
                                                        'custom_fields': custom_fields})


@login_required(login_url="/account/login")
def edit_breed_form(request, breed_id):
    # check if user has permission
    if request.method == 'GET':
        if not has_permission(request, {'read_only': False, 'contrib': False, 'admin': True, 'breed_admin': False}):
            return redirect_2_login(request)
    elif request.method == 'POST':
        if not has_permission(request, {'read_only': False, 'contrib': False, 'admin': True, 'breed_admin': False}):
            raise PermissionDenied()
    else:
        raise PermissionDenied()
    
    breed = get_object_or_404(Breed, id=breed_id)
    attached_service = get_main_account(request.user)
    breed_form = BreedForm(request.POST or None, request.FILES or None, instance=breed)

    try:
        # get custom fields
        custom_fields = json.loads(breed.custom_fields)
    except json.decoder.JSONDecodeError:
        try:
            # get custom fields template
            custom_fields = json.loads(attached_service.custom_fields)
        except json.decoder.JSONDecodeError:
            custom_fields = {}

    if request.method == 'POST':
        if 'delete' in request.POST:
            breed.delete()
            return HttpResponse(json.dumps({"result": "success"}))

        if breed_form.is_valid():
            # go through the input breed admins
            breed_admin_index = 0
            breed_admins = []
            while request.POST.get(f'breed_admin-{breed_admin_index}'):
                username = request.POST.get(f'breed_admin-{breed_admin_index}')
                breed_admin_index += 1
                
                # try to get the breed admin
                try:
                    breed_admin = User.objects.get(username=username)
                except User.DoesNotExist:
                    return HttpResponse(json.dumps({"result": "fail", "msg": f"{username} is not a user!"}))
                
                # check they're not the owner
                if breed_admin == attached_service.user.user:
                    return HttpResponse(json.dumps({"result": "fail", "msg": f"{username} is the owner of the account!"}))
                
                # remove from admins, if they're there
                if breed_admin in attached_service.admin_users.all():
                    attached_service.admin_users.remove(breed_admin)

                # remove from contributors, if they're there
                if breed_admin in attached_service.contributors.all():
                    attached_service.contributors.remove(breed_admin)

                # remove from read_only_users, if they're there
                if breed_admin in attached_service.read_only_users.all():
                    attached_service.read_only_users.remove(breed_admin)
                
                # append breed admin to list
                breed_admins.append(breed_admin)
            
            breed_form.save()

            for id, field in custom_fields.items():
                custom_fields[id]['field_value'] = request.POST.get(custom_fields[id]['fieldName'])

            breed.custom_fields = json.dumps(custom_fields)
            
            # flush breed admins
            breed.breed_admins.clear()
            
            # add breed admins to breed, and save
            for breed_admin in breed_admins:
                breed.breed_admins.add(breed_admin)
            
            # save and return success
            breed.save()
            return HttpResponse(json.dumps({"result": "success"}))
        else:
            print('tits')

    else:
        breed_form = BreedForm()

    return render(request, 'edit_breed_form.html', {'breed_form': breed_form,
                                                    'breed': breed,
                                                    'custom_fields': custom_fields})


@login_required(login_url="/account/login")
def view_breed(request, breed_id):
    attached_service = get_main_account(request.user)
    breed = Breed.objects.get(account=attached_service, id=breed_id)

    # get custom fields
    try:
        custom_fields = json.loads(breed.custom_fields)
    except json.decoder.JSONDecodeError:
        custom_fields = {}

    return render(request, 'breed.html', {'breed': breed,
                                          'custom_fields': custom_fields})

breed/templates/breed.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-6 col-8 justify-content-center">
            <h3 class="text-themecolor m-b-0 m-t-0">{{ breed.breed_name }}</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{% url 'breeds' %}">Breed{% if service.service.multi_breed %}s{% endif %}</a></li>
                <li class="breadcrumb-item active">{{ breed.breed_name }}</li>
            </ol>
        </div>
        <div class="col-md-6 col-4 justify-content-center">
            {% if add_breed %}
                {% if editor %}
                    <a href="{% url 'new_breed_form' %}" class="btn float-end hidden-sm-down btn-success"><i class="fad fa-plus-square"></i> Create
                    </a>
                    <a href="{% url 'edit_breed_form' breed.id %}" id="editBreed" class="btn btn-outline-info float-end mr-1"><i class="fad fa-pencil-alt"></i> Edit
                    </a>
                {% else %}
                    {% include 'login_modal.html' %}
                    <!-- /.modal -->
                    <button class="btn float-end hidden-sm-down btn-success" data-toggle="modal" data-target="#login"><i class="fad fa-plus-square"></i> Create</button>
                {% endif %}
            {% else %}
                {% include 'upgrade_modal.html' with type='breeds' %}
                <button class="btn float-end hidden-sm-down btn-success" data-toggle="modal" data-target="#upgrade"><i class="fad fa-plus-square"></i> Create</button>
                {% if editor %}
                    <a href="{% url 'edit_breed_form' breed.id %}" class="btn btn-outline-info float-end mr-2"><i class="fad fa-pencil-alt"></i> Edit
                    </a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->

    <div class="row">
        <div class="col-12 mt-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ breed.breed_name|title }} Details</h4>
                    <h6 class="card-subtitle mb-2 text-muted"></h6>
                    {% if breed.image %}
                        <img src="{{ breed.image.url }}" style="max-width:350px" class="float-left pr-2">
                    {% endif %}
                    <p class="card-text">{{ breed.breed_description|linebreaks }}</p>
                    <div class="row">
                        <div class="col-12 mt-2">
                            <dl>
                                {% if custom_fields %}
                                    {% for field_key, field_vals in custom_fields.items %}
                                        {% if field_vals.location == 'breed' %}
                                            <dt>{{ field_vals.fieldName }}</dt>
                                            <dd>{% if field_vals.field_value %}{{ field_vals.field_value }}{% else %}<br>{% endif %}</dd>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

breed/templates/breeds.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-6 col-8 justify-content-center">
            <h3 class="text-themecolor m-b-0 m-t-0">{% if service.site_mode == 'mammal' %}Pedigree {% else %}Poultry {% endif %} Breeds</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li class="breadcrumb-item active">Breed{% if service.service.multi_breed %}s{% endif %}</li>
            </ol>
        </div>
        <div class="col-md-6 col-4 justify-content-center">
            {% if add_breed %}
                {% if editor %}
                    <a href="{% url 'new_breed_form' %}" class="btn float-end hidden-sm-down btn-success"><i class="fad fa-plus-square"></i> Create
                    </a>
                {% else %}
                    {% include 'login_modal.html' %}
                    <!-- /.modal -->
                    <button class="btn float-end hidden-sm-down btn-success" data-toggle="modal" data-target="#login"><i class="fad fa-plus-square"></i> Create</button>
                {% endif %}
            {% else %}
                {% include 'upgrade_modal.html' with type='breeds' %}
                <button class="btn float-end hidden-sm-down btn-success" data-toggle="modal" data-target="#upgrade"><i class="fad fa-plus-square"></i> Create</button>
            {% endif %}

        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->

    <div class="row">
        {% for breed in breeds.all %}
            <!-- column -->
            <div class="col-lg-3 col-md-6 img-responsive">
                <!-- Card -->
                <div class="card">
                    <img class="card-img-top img-responsive" src="{% if breed.image %}{{ breed.image.url }}{% else %}{% static 'assets/images/default-breed.jpeg' %}{% endif %}" alt="{{ breed.breed_name|title }}">
                    <div class="card-body">
                        <h4 class="card-title">{{ breed.breed_name|title }}</h4>
                        <p class="card-text">{{ breed.description|truncatewords:50|linebreaks }}</p>
                        <a href="{% url 'view_breed' breed.id %}" class="btn btn-outline-success"><i class="far fa-eye"></i> View</a>
                        {% if editor %}
                            <a href="{% url 'edit_breed_form' breed.id %}" class="btn btn-outline-info"><i class="fad fa-pencil-alt"></i> Edit
                            </a>
                        {% else %}
                            <button class="btn btn-outline-info" data-toggle="modal" data-target="#login"><i class="fad fa-pencil-alt"></i> Edit</button>
                        {% endif %}
                    </div>
                </div>
                <!-- Card -->
            </div>
            <!-- column -->
        {% endfor %}
    </div>

{% endblock %}

breed/templates/new_breed_form.html
{% load static %}
{% load widget_tweaks %}
<h3 class="box-title">Breed Info</h3>
<hr class="mt-0 mb-5">
{% if breed_form.errors %}
    {% for field in breed_form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}: {{ error }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in breed_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<div class="row">
    {% for hidden in breed_form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in breed_form.visible_fields %}
    <div class="col-lg-6 col-md-12">
        <div class="form-group row">
            <label class="col-sm-3 text-right col-form-label">{% if 'Group' not in field.label %}{{ field.label|title }}{% endif %}</label>
            <div class="col-md-9">
                {% if field.label == 'Custom fields' %}
                    {% if custom_fields %}
                        {% for field_key, field_vals in custom_fields.items %}

                            {% if field_vals.location == 'breed' %}
                                {% if field_vals.fieldType == 'textField' %}
                                    <label class="col-sm-6 col-form-label">{{ field_vals.fieldName }}</label>
                                    <input id="{{ field_vals.id }}" class="form-control" name='{{ field_vals.fieldName }}' type="text">
                                {% elif field_vals.fieldType == 'textBox' %}
                                    <label class="col-sm-6 col-form-label">{{ field_vals.fieldName }}</label>
                                    <textarea id="{{ field_vals.id }}" name='{{ field_vals.fieldName }}' class="form-control"></textarea>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        {% if 'account/setup' not in request.path %}
                            <small>No custom fields added, <a href="{% url 'settings' %}">add some</a>?</small>
                        {% else %}
                            <small>Make sure you add some custom fields in the 'Site Settings' section after this!</small>
                        {% endif %}
                    {% endif %}
                {% elif "Mean Kinship" in field.label %}
                    {% if service.metrics %}
                        {{ field|attr:"class:form-control" }}
                        {{ field.help_text }}
                    {% else %}
                        <p class="text-danger mt-3">Metrics not enabled</p>
                        <p class="">This feature is available for Small Society, Large Society and Organisation accounts.
                            Metrics can be enabled in the <a href="{% url 'settings' %}">Site Settings</a> section.</p>
                    {% endif%}
                {% elif "Breed admins" in field.label %}
                    <div class="row pr-4">
                        <div class="col-10 pr-0">
                            <div id="users" class="input-group">
                                <input id="id_breed_admin" type="text" class="typeahead form-control" placeholder="Breed Admin">
                            </div>
                        </div>
                        <div class="col-2 pl-0">
                            <button id="addBreedAdminBtn" class="btn btn-info" type="button">Add</button>
                        </div>
                    </div>
                    <small>Enter a user to include in the breed admins of the breed.</small>
                    <!-- hidden note which will show name of breed admin if username has a match, or suggestions if partial match -->
                    <ul class="list-icons d-none" id="breed_admin-info"></ul>
                    <!-- hidden list to display selected breed admins -->
                    <div id="breedAdminsList">
                        {% for breed_admin in breed.breed_admins.all %}
                            <div id="breed_admin-{{ breed_admin.username }}" class="input-group">
                                <input value="{{ breed_admin.username }}" type="text" class="form-control" aria-describedby="basic-addon2" readonly>
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="button" onclick="removeBreedAdmin('breed_admin-{{ breed_admin.username }}')">Remove</button>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    {% if 'Group' not in field.label %}
                        {{ field|attr:"class:form-control" }}
                        {{ field.help_text }}
                        {% if field.label == 'Breed description' %}
                            <div id="charNum"></div>
                        {% endif %}
                    {% endif %}
                {% endif %}
                {% for error in field.errors %}
                  <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% block footer %}
    <script src="{% static 'assets/plugins/typeahead.js-master/dist/typeahead.bundle.min.js' %}"></script>
    <script>
        $('#id_breed_description').keyup( function() {
            var max = 2000;
                var len = $(this).val().length;
                if (len >= max) {
                    $('#charNum').text(' you have reached the limit').fadeIn();
                } else {
                    var char = max - len;
                    $('#charNum').text(char + ' characters left').fadeIn();
            }
        });
    </script>
{% endblock %}