api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('large-tier-queue', views.LargeTierQueueViews)
router.register('report-queue', views.ReportQueueViews)
router.register('pedigrees', views.PedigreeViews, basename='Pedigree')
router.register('pedigree-images', views.PedigreeImageViews, basename='PedigreeImage')
router.register('breeders', views.BreederViews, basename='Breeder')
router.register('breeds', views.BreedViews, basename='Breed')
router.register('breed-groups', views.BreedGroupViews, basename='BreedGroup')
router.register('services', views.ServicesViews, basename='services')
router.register('faq', views.FaqViews, basename='faq')
router.register('bolton', views.BoltonViews, basename='bolton')
router.register('kinship', views.KinshipViews, basename='kinship')
router.register('data_validation', views.DataValidatorViews, basename='data_validation')
router.register('stud_advisor', views.StudAdvisorViews, basename='stud_advisor')
router.register('attached-service', views.AttachedServiceViews, basename='AttachedService')
router.register('birth_notification', views.BirthNotificationViews, basename='BirthNotification')
router.register('bn_child', views.BnChildViews, basename='BnChild')
router.register('updates', views.UpdateViews, basename='updates')
#router.register('authenticate', views.Authenticate)

urlpatterns = [
    path('', include(router.urls)),
    path('api-token-auth', views.CustomAuthToken.as_view()),
    path('membership-add-edit-user', views.membership_add_edit_user)
]

cloudlines/urls.py
from django.contrib import admin
from django.urls import path, include
from cloud_lines import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('extras/', views.extras, name='extras'),
    path('faqs/', views.faqs, name='faqs'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('order/', views.order, name='order'),
    path('order/<int:service>', views.order, name='order'),
    path('blog/', views.blog, name='blog'),
    path('blog-article/<int:id>/<str:title>', views.blog_article, name='blog_article'),
    path('delete_blog/<int:id>', views.delete_blog, name='delete_blog'),
    path('privacy-policy/', views.privacy_policy, name='privacy'),
    path('know_more/', views.know_more, name='know_more'),
    path('order/subscribe', views.order_subscribe, name='order_subscribe'),
    path('order/success/<int:attached_service_id>/', views.order_success, name='order_success'),
    path('pedigree/', include('pedigree.urls')),
    path('breeders/', include('breeder.urls')),
    path('breeds/', include('breed.urls')),
    path('breed_groups/', include('breed_group.urls')),
    path('account/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('support/', include('support.urls')),
    path('impex/', include('impex.urls')),
    path('approvals/', include('approvals.urls')),
    path('dashboard', views.dashboard, name='dashboard'),
    path('select_graph', views.select_graph, name='select_graph'),
    path('api/', include('api.urls')),
    path('metrics/', include('metrics.urls')),
    path('bolton/', include('boltons.urls')),
    path('birth_notification/', include('birth_notifications.urls')),
    path('memberships/', include('memberships.urls')),
    path('reports/', include('reports.urls')),
    path('primary_account/<str:service>', views.activate_primary_account, name='primary_account'),
    path('build/<int:build_id>', views.build, name='build'),
    path('get_build_status', views.get_build_status, name='get_build_status'),
    path('gdpr/', views.gdpr, name='gdpr'),
    path('robots.txt', views.robots)
]

pedigree/urls.py
from django.urls import path
from . import tabledata
from . import views
from . import pedigree_charging

urlpatterns = [
    path('search', views.search, name='pedigree_search'),
    path('<int:pedigree_id>', views.ShowPedigree.as_view(), name='pedigree'),
    path('new_pedigree/', views.new_pedigree_form, name='new_pedigree_form'),
    path('<int:id>/edit_pedigree/', views.edit_pedigree_form, name='edit_pedigree_form'),
    path('<int:id>/image_upload_pedigree/', views.image_upload, name='image_upload'),
    path('<int:pedigree_id>/add_existing', views.add_existing, name='add_existing'),
    path('<int:pedigree_id>/add_existing_parent', views.add_existing_parent, name='add_existing_parent'),
    path('<int:pedigree_id>/certificate/<str:type>', views.GenerateCert.as_view(), name='cert'),
    path('get-pedigrees', tabledata.get_pedigrees, name="get_pedigrees"),
    path('get_pedigree_details', views.get_pedigree_details, name="get_pedigree_details"),
    path('get-ta-pedigrees/<str:sex>/<str:state>/<str:avoid>', tabledata.get_ta_pedigrees, name="get_ta_pedigrees"),
    path('pedigree_payment_settings', pedigree_charging.PedigreePaymentSettings.as_view(), name="pedigree_payment_settings"),
    path('pedigree_price_edit', pedigree_charging.pedigree_price_edit, name="pedigree_price_edit"),
    path('pedigree_checkout/<int:id>/<str:price>', views.pedigree_checkout, name="pedigree_checkout"),
    path('pedigree_checkout_session/<int:id>/<str:price>', pedigree_charging.pedigree_charging_session, name="pedigree_charging_session"),
    path('pedigree_paid', pedigree_charging.pedigree_paid, name="pedigree_paid"),
]

breed/models.py
from django.db import models
from account.models import AttachedService
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    return 'acc_{0}_{1}/{2}'.format(instance.account.id, instance.account.domain.replace('https://', ''), filename)


class Breed(models.Model):
    account = models.ForeignKey(AttachedService, on_delete=models.SET_NULL, blank=True, null=True)
    breed_name = models.CharField(max_length=100)
    image = models.ImageField(blank=True, upload_to=user_directory_path)
    breed_description = models.TextField(max_length=2000, blank=True)
    custom_fields = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    mk_threshold = models.DecimalField(max_digits=6, decimal_places=4, verbose_name='Mean Kinship threshold',
                                       help_text="This value dictates how potential males are selected when compared"
                                                 "with females. The MK value of the selected female, plus or minus"
                                                 " this figure, determines the acceptable range of MK values in the "
                                                 "male population, for a breeding match.",
                                       blank=True, null=True, default=0.0000)

    breed_admins = models.ManyToManyField(User, related_name='breed_admins', blank=True)

    def __str__(self):
        return self.breed_name

pedigree/models.py
from django.db import models
from django.contrib.auth.models import User
from breeder.models import Breeder
from breed.models import Breed
from account.models import AttachedService
from django.core.validators import MaxValueValidator, MinValueValidator


class Pedigree(models.Model):
    class Meta:
        ordering = ['-reg_no']

    STATES = (
        ('edited', 'Edited'),
        ('unapproved', 'Unapproved'),
        ('approved', 'Approved'),
    )
    state = models.CharField(max_length=10, choices=STATES, null=True, default='approved', verbose_name="State")
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Creator")
    account = models.ForeignKey(AttachedService, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Account")
    breeder = models.ForeignKey(Breeder, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Breeder", help_text="Often the same as Current Owner")
    current_owner = models.ForeignKey(Breeder, on_delete=models.SET_NULL, blank=True, null=True, related_name='owner', verbose_name='Current Owner', help_text="Often the same as Breeder")
    reg_no = models.CharField(max_length=100, blank=True, unique=True, verbose_name='Registration Number', help_text="Must be unique")
    tag_no = models.CharField(max_length=100, blank=True, null=True, verbose_name='Tag Number')
    name = models.CharField(max_length=100, blank=True, verbose_name="Name")
    description = models.TextField(max_length=1000, blank=True, null=True, verbose_name="Description", help_text="Max 1000 characters")
    date_of_registration = models.DateField(blank=True, null=True, verbose_name='Date of Registration', help_text="Date formats: 1984/09/31, 84/09/31, 31/09/1984, 31/09/84, 1984-09-31, 84-09-31, 31-09-1984, 31-09-84")
    dob = models.DateField(blank=True, null=True, verbose_name='Date of Birth', help_text="Date formats: 1984/09/31, 84/09/31, 31/09/1984, 31/09/84, 1984-09-31, 84-09-31, 31-09-1984, 31-09-84")
    dod = models.DateField(blank=True, null=True, verbose_name='Date of Death', help_text="Date formats: 1984/09/31, 84/09/31, 31/09/1984, 31/09/84, 1984-09-31, 84-09-31, 31-09-1984, 31-09-84")

    STATUSES = (
        ('dead', 'Dead'),
        ('alive', 'Alive'),
        ('unknown', 'Unknown'),
    )

    status = models.CharField(max_length=10, choices=STATUSES, null=True, default='unknown',
                           help_text="Accepted formats: dead, alive, unknown", verbose_name="Status")

    GENDERS = (
        ('male', 'Male'),
        ('female', 'Female'),
        ('castrated', 'Castrated'),
        ('unknown', 'Unknown')
    )

    sex = models.CharField(max_length=10, choices=GENDERS, null=True, default='unknown', 
                            help_text="Accepted formats: male, female, castrated, unknown", verbose_name="Sex")

    litter_size = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(50)], default=1,
                            help_text="Accepted range: 1-50", verbose_name="Litter Size")

    parent_father = models.ForeignKey('self', related_name='father', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Father', help_text="This should be the parents registration number.")
    parent_father_notes = models.CharField(max_length=500, blank=True, null=True, verbose_name='Father Notes', help_text="Max 500 characters")
    parent_mother = models.ForeignKey('self', related_name='mother', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Mother', help_text="This should be the parents registration number.")
    parent_mother_notes = models.CharField(max_length=500, blank=True, null=True, verbose_name='Mother Notes', help_text="Max 500 characters")
    breed_group = models.CharField(max_length=255, blank=True, null=True, verbose_name='Breed Group')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, blank=True, null=True, related_name='Breed', verbose_name="Breed")
    coi = models.DecimalField(decimal_places=4, max_digits=5, default=0, blank=True, verbose_name="COI")
    mean_kinship = models.DecimalField(decimal_places=4, max_digits=5, default=0, blank=True, verbose_name="Mean Kinship")
    # hidden
    date_added = models.DateTimeField(auto_now_add=True, verbose_name="Date Added")
    custom_fields = models.TextField(blank=True, verbose_name="Custom Fields")
    sale_or_hire = models.BooleanField(default=False, help_text="Is the pedigree for sale/hire, or not?", verbose_name="For Sale/Hire")
    paid = models.BooleanField(default=False)
    stripe_payment_token = models.CharField(max_length=255, blank=True, null=True)

    def parent_father_reg_no(self):
        if self.parent_father:
            return self.parent_father.reg_no

    def parent_father_name(self):
        if self.parent_father:
            return self.parent_father.name

    def parent_mother_reg_no(self):
        if self.parent_mother:
            return self.parent_mother.reg_no

    def parent_mother_name(self):
        if self.parent_mother:
            return self.parent_mother.name

    def breeder_breeding_prefix(self):
        if self.breeder:
            return self.breeder.breeding_prefix

    def current_owner_breeding_prefix(self):
        if self.current_owner:
            return self.current_owner.breeding_prefix

    def breed_breed_name(self):
        if self.breed:
            return self.breed.breed_name

    def __str__(self):
        return self.reg_no


def user_directory_path(instance, filename):
    return 'acc_{0}_{1}/{2}'.format(instance.account.id, instance.account.domain.replace('https://', ''), filename)


class PedigreeImage(models.Model):
    STATES = (
        ('edited', 'Edited'),
        ('unapproved', 'Unapproved'),
        ('approved', 'Approved'),
    )
    state = models.CharField(max_length=10, choices=STATES, null=True, default='approved')
    reg_no = models.ForeignKey(Pedigree, related_name='images', on_delete=models.SET_NULL, blank=True, null=True)
    account = models.ForeignKey(AttachedService, on_delete=models.SET_NULL, blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path)
    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return str(self.reg_no)

pedigree/forms.py
from django import forms


class PedigreeForm(forms.Form):

    breeder = forms.CharField(required=True)

    current_owner = forms.CharField(required=True)

    reg_no = forms.CharField(label='Registration Number', required=True)
    reg_no.widget.attrs['class'] = 'form-control'
    reg_no.widget.attrs['placeholder'] = 'R012345'

    tag_no = forms.CharField(label='Tag Number', required=False)
    tag_no.widget.attrs['class'] = 'form-control'
    #tag_no.widget.attrs['placeholder'] = 'T012345'

    name = forms.CharField(label='Name', required=False)
    name.widget.attrs['class'] = 'form-control'

    date_of_registration = forms.DateField(required=False, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_registration.widget.attrs['class'] = 'form-control'
    date_of_registration.widget.attrs['placeholder'] = 'dd/mm/yyyy'

    date_of_birth = forms.DateField(required=False, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_birth.widget.attrs['class'] = 'form-control'

    STATUSES = (
        ('dead', 'Dead'),
        ('alive', 'Alive'),
        ('unknown', 'Unknown'),
    )

    status = forms.ChoiceField(choices=STATUSES,  widget=forms.RadioSelect(attrs={'class': 'radio radio-info'}), initial='unknown', required=True)

    GENDERS = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('castrated', 'Castrated'),
        ('unknown', 'Unknown')
    ]
    sex = forms.ChoiceField(choices=GENDERS, widget=forms.RadioSelect(attrs={'class': 'radio radio-info'}), initial='unknown', required=True)

    LITTERSIZE = [tuple([x, x]) for x in range(1, 51)]
    litter_size = forms.IntegerField(widget=forms.Select(choices=LITTERSIZE), required=True)

    father = forms.CharField(required=False)
    father_notes = forms.CharField(required=False)
    father_notes.widget.attrs['class'] = 'form-control'

    mother = forms.CharField(required=False)
    mother_notes = forms.CharField(required=False)
    mother_notes.widget.attrs['class'] = 'form-control'

    breed_group = forms.CharField(required=False)

    description = forms.CharField(widget=forms.Textarea, required=False)
    description.widget.attrs['class'] = 'form-control'

    date_of_death = forms.DateField(required=False, widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_death.widget.attrs['class'] = 'form-control'
    date_of_death.widget.attrs['placeholder'] = 'dd/mm/yyyy'

    custom_fields = forms.CharField(widget=forms.Textarea, required=False)
    custom_fields.widget.attrs['class'] = 'form-control'

    breed = forms.CharField(required=True)

    sale_or_hire = forms.BooleanField(required=False)
    sale_or_hire.widget.attrs['class'] = 'form-control'

    registration_charge = forms.CharField(required=False)
    registration_charge.widget.attrs['class'] = 'form-select'


class ImagesForm(forms.Form):

    upload_images = forms.ImageField(required=False)
    upload_images.widget.attrs['class'] = 'form-control'
    upload_images.widget.attrs['multiple'] = ''

pedigree/templates/add_new_pedigree.html
{% if editor or contributor or breeds_editable|length > 0 %}
    <a href="{% url 'new_pedigree_form' %}{% if parent %}?parent={{ parent }}{% endif %}" class="btn btn-sm btn-outline-success waves-effect waves-light">
        <span class="btn-label"><i class="fad fa-plus-circle"></i></span> Add {% if service.site_mode == 'mammal' %}Pedigree{% else %}Bird{% endif %}</a>
{% else %}
    <button class="btn btn-sm btn-outline-success waves-effect waves-light" type="button" data-toggle="modal" data-target="#login">
        <span class="btn-label"><i class="fad fa-plus-circle"></i></span> Add {% if service.site_mode == 'mammal' %}Pedigree{% else %}Bird{% endif %}
    </button>
{% endif %}

pedigree/templates/new_pedigree_form_base.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <style>
        .container {
            display: table;
            width:100%;
            height: 100%;
        }

        input[type=button] {
            vertical-align: middle;
            display: block;
            width: 50%;
            margin: 0 auto;
        }

        .button-wrapper {
            display: table-cell;
            vertical-align: bottom;

        }
    </style>
{% endblock %}

{% block content %}
{% if add_pedigree %}
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-6 col-8 justify-content-center">
            <h3 class="text-themecolor m-b-0 m-t-0">New {% if service.site_mode == 'mammal' %}Pedigree {% else %}Bird {% endif %} Form</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{% url 'pedigree_search' %}">{% if service.site_mode == 'mammal' %}Pedigree {% else %}Poultry {% endif %} search</a></li>
                <li class="breadcrumb-item active">New {% if service.site_mode == 'mammal' %}Pedigree {% else %}Bird {% endif %} Form</li>
            </ol>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- Confirm submission moal -->
    <div id="save_ped_modal" class="modal fade confirmForm" tabindex="-1" role="dialog" aria-labelledby="confirmForm" aria-hidden="true" style="display: none;">
         <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to save this pedigree?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
                    <button id="confirmSaveBtn" type="button" class="btn btn-success waves-effect waves-light">Save Pedigree</button>
                </div>
                <script>
                    // $('#confirmSaveBtn').click(function () {
                    //     $('#newPedigreeForm').submit();
                    // });
                </script>
            </div>
        </div>
    </div>
    <!-- add new breeder modal content -->
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="newBreederModal" aria-hidden="true" style="display: none;">
         <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <form id="breederForm">
                        {% include 'new_breeder_form.html' %}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
                    <button id="saveBreeder" type="button" class="btn btn-success waves-effect waves-light">Save breeder</button>
                </div>
                <script>
                    $('#saveBreeder').click(function () {
                        var local = breeders;
                        var data = $('#breederForm').serialize();
                        $.ajax({
                            url: '{% url 'new_breeder_form' %}',
                            type: 'post',
                            dataType: 'text',
                            headers: {'X-CSRFToken': document.getElementsByName('csrfmiddlewaretoken')[0].value},
                            data: data,
                            beforeSend: function() {
                                // setting a timeout
                                if ($('#id_breeding_prefix').val().trim() == '') {
                                    $("#id_breeding_prefix").css({"border-color": "red"});;
                                    return false;
                                }
                            },
                            success: function(data) {
                                // display error message
                                infoMsg("New breeder added!");
                                $('#showNewBreederModal').click();
                            },
                            error: function(jqXHR, textStatus, errorThrown){
                            }
                        });
                    });

                    var fadeout = 100;
                    $('#id_breeding_prefix').keyup( function() {
                        $.ajax({
                            url: '{% url 'breeder_check' %}',
                            type: 'post',
                            dataType: 'text',
                            data: $('#id_breeding_prefix').serialize(),
                            success: function(data) {
                            if (data == 'False') {
                                $('#saveBreeder').attr('disabled', false);
                                $('#breeding_prefixMessage').html('');
                                } else {
                                $('#saveBreeder').attr('disabled', true);
                                $('#breeding_prefixMessage').html('<i class="icon-warning-sign"></i> <strong>Warning!</strong> Breeding prefix is already in use!').css('color', 'red');
                                }
                             },
                            error: function(jqXHR, textStatus, errorThrown){
                                console.log('jqXHR:');
                                console.log(jqXHR);
                                console.log('textStatus:');
                                console.log(textStatus);
                                console.log('errorThrown:');
                                console.log(errorThrown);
                            }
                        });
                    });
                </script>
            </div>
        </div>
    </div>
    <!-- /.modal -->
    <!-- add new breed modal content -->
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" id="newBreedModal" aria-labelledby="newBreedModal" aria-hidden="true" style="display: none;">
         <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <form id="breedForm" action="{% url 'new_breed_form' %}" method="POST" target="dummyframe" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'new_breed_form.html' %}
                    </form>
                    <iframe width="0" height="0" border="0" name="dummyframe" id="dummyframe"></iframe>
                </div>
                <div class="modal-footer">
                    <button id="closeBreed" type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
                    <button id="saveBreed" type="button" class="btn btn-success waves-effect waves-light">Save breed</button>
                </div>
                <script>
                    $('#saveBreed').click(function () {
                        var local = breeds;
                        breeds.push($('#id_breed_name').val());
                        $("#breedForm").submit();
                        $('#closeBreed').click();
                        $('#id_breed').val($('#id_breed_name').val());
                    });
                </script>
            </div>
        </div>
    </div>
    <!-- /.modal -->

    <div class="container pt-5">
        <div class="card ">
            <div class="card-header">
                <h4 class="mb-0 ">Add New {% if service.site_mode == 'mammal' %}Pedigree {% else %}Bird {% endif %} Form</h4>
            </div>
            <div class="card-body">
                <form id="newPedigreeForm" action="{% url 'new_pedigree_form' %}" method="POST" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-body">
                        {% include 'new_pedigree_form.html' %}
                    </div>
                    <hr>
                </form>
                <div class="form-actions">
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <div class="row container">
                                <div class="col-md-offset-3 col-md-9 button-wrapper">
                                    <button id="submitPedigree" data-toggle="modal" data-target=".confirmForm" class="btn btn-success">{% if contributor %}Submit for approval{% else %}Submit{% endif %}</button>
                                    <a href="{% url 'pedigree_search' %}"><button type="button" class="btn btn-inverse">Cancel</button></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6"> </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
<h1>Oops, you shouldn't be here!</h1>
{% endif %}

{% endblock %}

{% block footer %}
<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
<link
  rel="stylesheet"
  href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css"
  type="text/css"
/>
<script>
    $("#confirmSaveBtn").on("click", function(e) {
        e.preventDefault();

        $.ajax({
            url: "{% url 'new_pedigree_form' %}",
            type: 'post',
            dataType: 'text',
            data: $('#newPedigreeForm').serialize(),
            success: function(data) {
                var result = JSON.parse(data);
                if (result.result == 'success') {
                    // redirect to breeders page
                    window.location.replace("/pedigree/" + result.ped_id);
                } else if (result.result == 'payment_redirect') {
                    window.location.replace(result.url);
                } else {
                    // create html to display what fields were erroneous
                    var errorHtml = "";
                    if (result.errors) {
                        errorHtml = errorHtml + '<h5 class="text-danger">Your form had the following errors:</h5>';
                        console.log(Object.keys(result.errors.field_errors).length)
                        // go through field errors
                        if (Object.keys(result.errors.field_errors).length > 0) {
                            errorHtml = errorHtml + '<br/><ul>';

                            // add each field and error to the errors
                            result.errors.field_errors.forEach( error => {
                                errorHtml = errorHtml + '<li>' + error.field + ': ' + error.error + '</li>';
                            });

                            errorHtml = errorHtml + '</ul>';
                        }

                        // go through invalid fields
                        if (result.errors.non_field_errors.length > 0) {
                            errorHtml = errorHtml + '<br/><ul>';

                            result.errors.non_field_errors.forEach( error => {
                                errorHtml = errorHtml + '<li>' + error + '</li>';
                            });

                            errorHtml = errorHtml + '</ul>';
                        }
                    }
                    // add html to section
                    $('#errors').html(errorHtml);

                    // display errors section
                    $('#errors').removeClass('d-none');

                    // remove modal
                    $('#save_ped_modal').modal('hide');
                    
                    // display error message
                    errorMsg("Your form had errors!");
                }
            },
            error: function(jqXHR, textStatus, errorThrown){
                console.log('jqXHR:');
                console.log(jqXHR);
                console.log('textStatus:');
                console.log(textStatus);
                console.log('errorThrown:');
                console.log(errorThrown);
            }
        });
    });
</script>

{% endblock %}

pedigree/templates/pedigree_table.html
{% load custom_tags %}

<table id="{{ table_id }}" class="table table-bordered table-striped">
    <thead>
        <tr>
            {% for col in columns %}
                {% for ped_col, data in column_data.items %}
                    {% if col == data.db_id %}
                        <th scope="col">{{ data.name }}</th>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for pedigree in pedigrees.all %}
            <tr {% if editor or contributor or breeds_editable|length > 0 and pedigree.breed__breed_name in breeds_editable %}onclick="window.location='{% url 'pedigree' pedigree.id %}';" style="cursor: pointer;"{% endif %}>
                {% for col in columns %}
                    {% for ped_col, data in column_data.items %}
                        {% if col == data.db_id %}
                            <th scope="row">
                                {% autoescape off %}
                                    {% pedigree_column_data pedigree data %}
                                {% endautoescape %}
                            </th>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>